### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-1-evaluacion-final-almudenabr#1]
Muy buen trabajo @almudenabr!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 373 / 429
- [ ] HTML > HAMBURGUESA: El menú de la hamburguesa debe tener un `nav`.

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te encaja dímelo cuanto antes por favor.

> Para corregir el ejercicio buscamos determinadas palabras en el código para identificar las secciones. Por ejemplo buscamos **Anonymous** para buscar el hero. Si has escrito mal alguna palabra en el código es posible que te aparezcan aquí falsos errores.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by almudenabr** [comment]
Buenos días Miguel!!
Tengo algunas dudas sobre los comentarios del issue:

- el 1º dice que debo tener 2 ficheros de estilos importados con un <link>, supongo que se refiere a la importación de las fuentes, yo lo importé con @import añadiéndolo a main.scss.....no es correcto hacerlo así, es mejor hacerlo con <link> en html?
- el 2º: todos los <img> deben tener <title>: en el ejercicio como los <img> los he metido dentro de los links <a>, le puse el <title> en <a>...el txt sí aparece cuando ponemos el cursor, pero es más correcto ponerlo en <img> o da igual?
- el 4º: sí tengo  transiciones y  animaciones

Muchas gracias!!!

**Comment by migueldelmazo** [comment]
Hola @almudenabr tienes toda la razón, ya he modificado el issue. Buen trabajo!!!
